"""
Tool: condition_lookup_tool
Agent: ResearchAgent
Student: Mihiraj

Looks up possible medical conditions matching a patient's symptoms.
Uses a local curated CSV as primary source and optionally calls the
free Open Disease API (no key required) as a secondary source.
"""

import csv
import json
import requests
from pathlib import Path
from typing import Optional

# Local fallback dataset — ships with the repo, no network needed
LOCAL_CONDITIONS_PATH = Path(__file__).parent.parent / "data" / "conditions.csv"

DISCLAIMER = (
    "⚠️  This output is generated by an AI system for educational purposes only. "
    "It is NOT a medical diagnosis. Always consult a qualified healthcare professional."
)


def _load_local_conditions() -> list[dict]:
    """Load the bundled conditions CSV into memory."""
    if not LOCAL_CONDITIONS_PATH.exists():
        _create_local_conditions_csv()

    with open(LOCAL_CONDITIONS_PATH, newline="", encoding="utf-8") as f:
        return list(csv.DictReader(f))


def _create_local_conditions_csv() -> None:
    """Bootstrap the local conditions dataset on first run."""
    rows = [
        {"condition", "symptom_keywords", "description"},
    ]
    # Write a curated seed dataset
    data = [
        ("Influenza",            "fever,headache,muscle pain,fatigue,cough,chills",
         "Viral infection affecting the respiratory system."),
        ("COVID-19",             "fever,cough,fatigue,shortness of breath,headache",
         "Respiratory illness caused by SARS-CoV-2."),
        ("Myocardial Infarction","chest pain,shortness of breath,nausea,sweating",
         "Heart attack — blocked coronary artery. EMERGENCY."),
        ("Pulmonary Embolism",   "chest pain,shortness of breath,dizziness",
         "Blood clot in pulmonary artery. Life-threatening."),
        ("Migraine",             "headache,nausea,blurred vision,dizziness",
         "Neurological condition causing severe recurring headaches."),
        ("Stroke",               "numbness,confusion,blurred vision,weakness,headache",
         "Interruption of blood supply to the brain. EMERGENCY."),
        ("Gastroenteritis",      "nausea,vomiting,diarrhea,abdominal pain,fever",
         "Inflammation of the stomach and intestines, usually viral."),
        ("Appendicitis",         "abdominal pain,nausea,vomiting,fever",
         "Inflammation of the appendix; may require surgery."),
        ("Pneumonia",            "cough,fever,shortness of breath,fatigue,chest pain",
         "Lung infection causing fluid accumulation in air sacs."),
        ("Anaphylaxis",          "rash,swelling,difficulty breathing,dizziness",
         "Severe allergic reaction. Requires immediate epinephrine."),
        ("Urinary Tract Infection","abdominal pain,fever,fatigue",
         "Bacterial infection of the urinary tract."),
        ("Common Cold",          "sore throat,runny nose,cough,fatigue",
         "Viral upper respiratory infection; self-limiting."),
        ("Hypertensive Crisis",  "headache,blurred vision,chest pain,dizziness",
         "Severely elevated blood pressure requiring urgent treatment."),
        ("Dehydration",          "dizziness,fatigue,headache,nausea",
         "Insufficient fluid intake or excessive fluid loss."),
        ("Epileptic Seizure",    "seizure,confusion,loss of consciousness",
         "Sudden electrical disturbance in the brain. EMERGENCY."),
    ]
    LOCAL_CONDITIONS_PATH.parent.mkdir(exist_ok=True)
    with open(LOCAL_CONDITIONS_PATH, "w", newline="", encoding="utf-8") as f:
        writer = csv.writer(f)
        writer.writerow(["condition", "symptom_keywords", "description"])
        writer.writerows(data)


def lookup_conditions(
    symptoms: list[str],
    max_results: int = 5,
) -> dict:
    """
    Return a ranked list of possible medical conditions matching the given symptoms.

    Matching is done by counting keyword overlaps between the patient's extracted
    symptoms and each condition's keyword list. Higher overlap → higher score.

    Args:
        symptoms:    List of symptom keyword strings from the IntakeAgent,
                     e.g. ["chest pain", "shortness of breath", "nausea"].
        max_results: Maximum number of conditions to return (default 5).

    Returns:
        A dict with keys:
            possible_conditions (list[dict])  – ranked conditions:
                [{name, description, match_score, matched_symptoms}]
            disclaimer          (str)         – mandatory AI disclaimer
            source              (str)         – "local_csv"

    Raises:
        ValueError: If symptoms is empty or max_results < 1.
    """
    if not symptoms:
        raise ValueError("symptoms list must not be empty.")
    if max_results < 1:
        raise ValueError("max_results must be at least 1.")

    conditions = _load_local_conditions()
    patient_symptoms = {s.lower().strip() for s in symptoms}

    scored: list[dict] = []
    for row in conditions:
        cond_keywords = {kw.strip() for kw in row["symptom_keywords"].split(",")}
        matched = patient_symptoms & cond_keywords
        score = len(matched)
        if score > 0:
            scored.append({
                "name": row["condition"],
                "description": row["description"],
                "match_score": score,
                "matched_symptoms": sorted(matched),
            })

    # Sort descending by match score
    scored.sort(key=lambda x: x["match_score"], reverse=True)
    top = scored[:max_results]

    return {
        "possible_conditions": top,
        "disclaimer": DISCLAIMER,
        "source": "local_csv",
    }
